Repository laynebritton/jl-fast-treecapitator, pull requests merged in 2023-10, with the labels that each got.

#30 Update for 1.20.40
  behavior_packs/jl-fast-treecapitator/manifest.json
Labels: bug, status: needs code review

#31 Implemented github actions for automatic builds and releases.
  .github/workflows/build.yml
  .github/workflows/release.yml
  behavior_packs/jl-fast-treecapitator/manifest.json
Labels: enhancement, status: complete

#26 User CLI Implementation.
  behavior_packs/jl-fast-treecapitator/manifest.json
  scripts/BlockBreakEvents/GetIdBreakEvent.ts
  scripts/Debug.ts
  scripts/DynamicProperties/AllowSet.ts
  scripts/DynamicProperties/JLTreeCapConfig.ts.ts
  scripts/UserCLI.ts
  scripts/Utilities.ts
  scripts/VeinBreakEvent.ts
  scripts/main.ts
Labels: enhancement, status: complete

#33 Remove faulty initialization logic from User Config
  behavior_packs/jl-fast-treecapitator/manifest.json
  scripts/main.ts
Labels: bug
